### ISSUE TITLE
is prefetch_count a supported option?

### ISSUE THREAD

**Issue by ThomasADavis** [logstash-plugins/logstash-mixin-rabbitmq_connection#5]
All connections from logstash2.0 to rabbitmq for input have a prefetch_count of 0, when the .rb file says it should be 256.

I can not find anywhere where this value is used in the either the input or the mixin rabbitmq plugins.

**Comment by borisyukd** [comment]
I added PR #6 for this issue

**Comment by andrewvc** [comment]
@borisyukd I sincerely apologize, but I was wrong when I suggested posting this issue here in this repo! It should have been only in the input repo (like it was originally). It obviously doesn't make sense for the output to have this option.

I've submitted a PR accomplishing this in https://github.com/logstash-plugins/logstash-input-rabbitmq/pull/46
